# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Simple-App
version:      0.01
version_from: App.pm
installdirs:  site
requires:
    Config::Simple:                

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
